// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "SSC_2025",
    platforms: [
        .iOS("17.0")
    ],
    products: [
        .iOSApplication(
            name: "SSC_2025",
            targets: ["AppModule"],
            bundleIdentifier: "Venkatesh-Devendran.SSC-2025",
            teamIdentifier: "3W9U482L92",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .asset("AccentColor"),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .landscapeRight,
                .landscapeLeft
            ],
            appCategory: .education
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .copy("Resources/explosion.sks"),
                .copy("Resources/spaceshipTrails.sks"),
                .copy("Resources/asteroidTrails.sks"),
                .copy("Resources/stars.sks"),
                .copy("Resources/BGPattern.sks"),
                .copy("Resources/shieldImpact.sks"),
                .copy("Resources/ProximaCentauri.sks"),
                
                .copy("Resources/type.mp3"),
                .copy("Resources/pew-pew.wav"),
                .copy("Resources/BGMusic.mp3"),

            ]
        )
    ],
    swiftLanguageVersions: [.v5]
)
